version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=sqlite:/app/data/ski.db
      - RUST_BACKTRACE=1
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ski_data:/app/data

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - api

volumes:
  ski_data:
